name: form_companion_presenter
description: >
  Helps building presenter for forms with validations in model layer
  including asynchronous validations, submittion button availability,
  etc.
version: 0.1.0
repository: https://github.com/yfakariya/form_companion_presenter

environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.15.0
  flutter:
    sdk: flutter
  meta: ^1.3.0

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_localizations:
    sdk: flutter
  flutter_test:
    sdk: flutter
