name: github_issues
description: A featured example of form_builder_companion_presenter usage in an application.

publish_to: 'none' 

version: 1.0.0

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.4
  easy_localization: ^3.0.0
  flutter:
    sdk: flutter
  flutter_form_builder: ^7.6.0
  flutter_riverpod: ^2.0.2
  flutter_secure_storage: ^6.0.0
  form_builder_companion_presenter:
    path: ../../packages/form_builder_companion_presenter
  form_builder_validators: ^8.3.0
  form_companion_presenter:
    path: ../../packages/form_companion_presenter
  freezed_annotation: ^2.2.0
  github: ^9.4.0
  go_router: ^5.1.1
  meta: ^1.7.0
  oauth2_client: ^3.0.0
  platform: ^3.1.0
  riverpod_annotation: ^1.0.0
  shared_preferences: ^2.0.5
  state_notifier: ^0.7.2+1

dev_dependencies:
  build_runner: ^2.2.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  form_companion_generator:
    path: ../../packages/form_companion_generator
  format: ^1.2.0
  freezed: ^2.2.0
  grinder: ^0.9.2
  path: ^1.8.1
  riverpod_generator: ^1.0.2 

flutter:
  uses-material-design: true
