name: form_companion_presenter_examples
description: Examples of form_companion_presenter.
publish_to: 'none' 
version: 0.1.0

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.4
  easy_localization: ^3.0.0
  flutter:
    sdk: flutter
  flutter_form_builder: ^7.1.1
  flutter_riverpod: ^1.0.3
  form_builder_companion_presenter:
    path: ../../packages/form_builder_companion_presenter
  form_builder_validators: ^7.6.1
  form_companion_presenter:
    path: ../../packages/form_companion_presenter
  freezed_annotation: ^1.1.0
  meta: ^1.7.0
  platform: ^3.1.0
  state_notifier: ^0.7.2+1

dev_dependencies:
  build_runner: ^2.1.7
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  format: ^1.1.1
  freezed: ^1.1.1
  grinder: ^0.9.0
  path: ^1.8.0

dependency_overrides: 
  form_builder_companion_presenter:
    path: ../../packages/form_builder_companion_presenter
  form_companion_presenter:
    path: ../../packages/form_companion_presenter

flutter:
  uses-material-design: true
