name: form_companion_presenter_examples
description: Examples of `form_companion_presenter` and `form_builder_companion_presenter`.
publish_to: 'none' 
version: 0.1.0

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: ">=3.7.0"

dependencies:
  cupertino_icons: ^1.0.0
  easy_localization: ^3.0.0
  flutter:
    sdk: flutter
  flutter_form_builder: ^7.7.0
  flutter_riverpod: ^2.2.0
  form_builder_companion_presenter:
    path: ../../packages/form_builder_companion_presenter
  form_builder_validators: ^8.4.0
  form_companion_presenter:
    path: ../../packages/form_companion_presenter
  freezed_annotation: ^2.2.0
  go_router: ^6.2.0
  meta: ^1.8.0
  platform: ^3.1.0
  riverpod_annotation: ^1.1.0

dev_dependencies:
  build_runner: ^2.3.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  form_companion_generator:
    path: ../../packages/form_companion_generator
  freezed: ^2.3.0
  grinder: ^0.9.3
  # Bound from flutter_test
  path: ^1.8.0
  riverpod_generator: ^1.2.0

flutter:
  uses-material-design: true
