name: form_companion_presenter_examples
description: Examples of form_companion_presenter.
publish_to: 'none' 
version: 0.1.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  easy_localization: ^3.0.0
  flutter:
    sdk: flutter
  flutter_form_builder: ^6.1.0+1
  flutter_riverpod: ^0.14.0+3
  form_builder_presenter_state_notifier:
    path: ../../packages/form_builder_presenter_state_notifier
  form_companion_presenter:
    path: ../../packages/form_companion_presenter
  form_presenter_state_notifier:
    path: ../../packages/form_presenter_state_notifier
  freezed_annotation: ^0.14.3
  meta: ^1.3.0
  state_notifier: ^0.7.0

dev_dependencies:
  build_runner: ^2.1.2
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  freezed: ^0.14.5

dependency_overrides: 
  form_builder_presenter_state_notifier:
    path: ../../packages/form_builder_presenter_state_notifier
  form_companion_presenter:
    path: ../../packages/form_companion_presenter
  form_presenter_state_notifier:
    path: ../../packages/form_presenter_state_notifier

flutter:
  uses-material-design: true
