name: form_builder_companion_presenter_example
description: An example project.

publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  cupertino_icons: ^1.0.5
  easy_localization: ^3.0.1
  flutter:
    sdk: flutter
  flutter_form_builder: ^7.7.0
  flutter_riverpod: ^2.1.3
  form_builder_companion_presenter:
    path: ../../form_builder_companion_presenter
  form_builder_validators: ^8.4.0
  form_companion_presenter:
    path: ../../form_companion_presenter
  freezed_annotation: ^2.2.0
  go_router: ^6.0.0
  meta: ^1.8.0
  platform: ^3.1.0
  riverpod_annotation: ^1.1.1

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

dependency_overrides: 
  form_companion_presenter:
    path: ../../form_companion_presenter

flutter:
  uses-material-design: true
