name: form_builder_companion_presenter_example
description: An example project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  easy_localization: ^3.0.0
  flutter:
    sdk: flutter
  flutter_form_builder : ^6.0.1
  flutter_riverpod: ^1.0.2
  form_builder_companion_presenter:
    path: ../../form_builder_companion_presenter
  form_companion_presenter:
    path: ../../form_companion_presenter
  freezed_annotation: ^1.1.0
  meta: ^1.3.0
  state_notifier: ^0.7.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

dependency_overrides: 
  form_companion_presenter:
    path: ../../form_companion_presenter

flutter:
  uses-material-design: true
