name: form_builder_companion_presenter_example
description: An example project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  easy_localization: ^3.0.0
  flutter:
    sdk: flutter
  flutter_form_builder : ^7.3.1
  flutter_riverpod: ^1.0.4
  form_builder_companion_presenter:
    path: ../../form_builder_companion_presenter
  form_builder_validators: ^8.1.1
  form_companion_presenter:
    path: ../../form_companion_presenter
  freezed_annotation: ^2.0.3
  go_router: ^4.0.0
  meta: ^1.3.0
  platform: ^3.1.0
  state_notifier: ^0.7.2+1

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

dependency_overrides: 
  form_companion_presenter:
    path: ../../form_companion_presenter

flutter:
  uses-material-design: true
