name: form_presenter_state_notifier
description: >
  Implements [form_companion_presenter](https://github.com/yfakariya/form_companion_presenter)
  with [state_notifier](https://pub.dev/packages/state_notifier)
version: 0.1.0
homepage: https://github.com/yfakariya/form_companion_presenter
repository: https://github.com/yfakariya/form_companion_presenter

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.5.0
  flutter:
    sdk: flutter
  form_companion_presenter: ^0.1.0
  meta: ^1.3.0
  state_notifier: ^0.7.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
