include: ../../../analysis_options.yaml

analyzer: 
  exclude: ['lib/generated_plugin_registrant.dart']
  errors:
    do_not_use_environment: ignore # riverpod_generator uses environment
    public_member_api_docs: ignore # overkill for examples
