name: form_companion_presenter_example
description: An example project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  easy_localization: ^3.0.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^1.0.3
  form_companion_presenter:
    path: ../../form_companion_presenter
  freezed_annotation: ^1.1.0
  meta: ^1.3.0
  platform: ^3.1.0
  state_notifier: ^0.7.2+1

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
