name: form_companion_generator_test_targets
description: >
  This is a dummy package to host sources for testing of form_companion_generator package.
version: 0.1.0
# Do not publish anywhere!
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_form_builder: ^7.7.0
  form_builder_companion_presenter:
  form_companion_presenter:
  # Align with flutter_form_builder
  intl: ^0.17.0
  meta: ^1.3.0

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints:  ^2.0.1
  form_companion_generator:
    path: ../../packages/form_companion_generator
  grinder: ^0.9.2
