name: form_companion_generator_test_targets
description: >
  This is a dummy package to host sources for testing of form_companion_generator package.
version: 0.0.1
# Does not publish anywhere!
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_form_builder: ^7.3.1
  form_builder_companion_presenter: 
  form_companion_presenter: 
  intl: ^0.17.0

dev_dependencies:
  build_runner: ^2.1.7
  flutter_lints:  ^2.0.1
  form_companion_generator:
    path: ../../packages/form_companion_generator
  grinder: ^0.9.1

dependency_overrides:
  form_builder_companion_presenter:
    path: ../../packages/form_builder_companion_presenter
  form_companion_presenter:
    path: ../../packages/form_companion_presenter
