name: form_companion_generator_test_targets
description: >
  This is a dummy package to host sources for testing of form_companion_generator package.
version: 0.0.1
# Does not publish anywhere!
publish_to: none

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_form_builder: ^7.1.1
  form_builder_companion_presenter: 
  form_companion_presenter: 

dev_dependencies:
  flutter_lints: ^1.0.0

dependency_overrides:
  form_builder_companion_presenter:
    path: ../../packages/form_builder_companion_presenter
  form_companion_presenter:
    path: ../../packages/form_companion_presenter
