name: form_field_builder_emitter
description: Logic for FormField builder grinder scripts.
version: 1.0.0

environment:
  sdk: '>=2.14.2 <3.0.0'

dependencies:
  analyzer: ^3.0.0
  grinder: ^0.9.0
  path: ^1.8.0

dev_dependencies:
  flutter_lints: ^1.0.0
