# Read about `build.yaml` at https://pub.dev/packages/build_config
builders:
  form_companion_generator:
    import: 'package:form_companion_generator/form_companion_generator.dart'
    builder_factories: ['generate']
    build_extensions: { '.dart': ['.fcp.dart'] }
    auto_apply: dependents
    build_to: source
    defaults:
      options:
        named_templates:
          label_template: '#PROPERTY#.name'
          hint_template: 'null'
          item_widget_template: 
              template: 'Text(#ITEM_VALUE_STRING#)'
              imports:
                Text: 'package:flutter/widgets.dart'
        argument_templates:
          default:
            autovalidateMode: '#ARGUMENT# ?? #AUTO_VALIDATE_MODE#'
            decoration: '#ARGUMENT# ?? #DEFAULT_VALUE_COPY_OR_NEW#(labelText: #LABEL_TEMPLATE#, hintText: #HINT_TEMPLATE#)'
          DropdownButtonFormField:
            items:
              item_template: 'DropdownMenuItem<#ITEM_VALUE_TYPE#>(value: #ITEM_VALUE#, child: #ITEM_WIDGET_TEMPLATE#)'
            onChanged: '#ARGUMENT# ?? (_) {}' # Tip: required to work correctly
          FormBuilderDropdown:
            items:
              item_template: 'DropdownMenuItem<#ITEM_VALUE_TYPE#>(value: #ITEM_VALUE#, child: #ITEM_WIDGET_TEMPLATE#)'
            onChanged: '#ARGUMENT# ?? (_) {}' # Tip: required to work correctly
          FormBuilderCheckboxGroup:
            options:
              item_template: 'FormBuilderFieldOption<#ITEM_VALUE_TYPE#>(value: #ITEM_VALUE#, child: #ITEM_WIDGET_TEMPLATE#)'
          FormBuilderChoiceChip:
            options:
              item_template: 'FormBuilderChipOption<#ITEM_VALUE_TYPE#>(value: #ITEM_VALUE#, child: #ITEM_WIDGET_TEMPLATE#)'
          FormBuilderFilterChip:
            options:
              item_template: 'FormBuilderChipOption<#ITEM_VALUE_TYPE#>(value: #ITEM_VALUE#, child: #ITEM_WIDGET_TEMPLATE#)'
          FormBuilderRadioGroup:
            options:
              item_template: 'FormBuilderFieldOption<#ITEM_VALUE_TYPE#>(value: #ITEM_VALUE#, child: #ITEM_WIDGET_TEMPLATE#)'
          FormBuilderSegmentedControl:
            options:
              item_template: 'FormBuilderFieldOption<#ITEM_VALUE_TYPE#>(value: #ITEM_VALUE#, child: #ITEM_WIDGET_TEMPLATE#)'
