name: form_companion_generator
description: >
  Code generator for `form_companion_presenter` and `form_builder_companion_presenter`.
version: 0.1.0
repository: https://github.com/yfakariya/form_companion_presenter

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  analyzer: ^3.3.1
  build: ^2.0.0
  build_config: ^1.0.0
  collection: ^1.15.0
  logging: ^1.0.2
  meta: ^1.7.0
  source_gen: ^1.2.0

dev_dependencies:
  build_resolvers: ^2.0.6
  build_runner: ^2.1.7
  build_test: ^2.1.5
  lints: ^1.0.1
  matcher: ^0.12.11
  path: ^1.8.0
  pub_semver: ^2.1.1
  source_gen_test: ^1.0.2
  test: ^1.20.1
  tuple: ^2.0.0
