name: form_companion_generator
description: >
  Code generator for form_companion_presenter and form_builder_companion_presenter to reduce boilerplate of forms.
version: 0.2.0
repository: https://github.com/yfakariya/form_companion_presenter

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  analyzer: ^5.1.0
  build: ^2.3.1
  build_config: ^1.1.1
  collection: ^1.16.0
  logging: ^1.1.0
  meta: ^1.8.0
  source_gen: ^1.2.6

dev_dependencies:
  build_resolvers: ^2.0.10
  build_runner: ^2.3.2
  build_test: ^2.1.5
  lints: ^2.0.0
  matcher: ^0.12.12
  path: ^1.8.2
  pub_semver: ^2.1.2
  source_gen_test: ^1.0.4
  test: ^1.21.6
  tuple: ^2.0.1
