name: form_companion_generator
description: >
  Code generator for form_companion_presenter and form_builder_companion_presenter to reduce boilerplate of forms.
version: 0.5.0+1
repository: https://github.com/yfakariya/form_companion_presenter
issue_tracker: https://github.com/yfakariya/form_companion_presenter/issues

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  # Align with freezed
  analyzer: ^5.2.0
  build: ^2.3.0
  build_config: ^1.1.0
  # Align with flutter
  collection: ^1.16.0
  logging: ^1.1.0
  # Align with freezed
  meta: ^1.7.0
  source_gen: ^1.2.0

dev_dependencies:
  build_resolvers: ^2.2.0
  build_runner: ^2.3.0
  build_test: ^2.1.0
  lints: ^2.0.0
  matcher: ^0.12.14
  # Align with flutter_test
  path: ^1.8.0
  pub_semver: ^2.1.0
  source_gen_test: ^1.0.0
  test: ^1.23.0
  tuple: ^2.0.0
