name: dev_env
description: Development environment setup script.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  grinder: ^0.9.2
  path: ^1.8.2

dev_dependencies:
  flutter_lints: ^2.0.1
