name: dev_env
description: Development environment setup script.
version: 1.0.0

environment:
  sdk: '>=2.14.2 <3.0.0'

dependencies:
  grinder: ^0.9.0
  path: ^1.8.0
  pubspec_parse: ^1.1.0
  yaml_edit: ^2.0.1

dev_dependencies:
  flutter_lints: ^1.0.0
