name: form_builder_companion_presenter
description: >
  Implements [form_companion_presenter](https://github.com/yfakariya/form_companion_presenter)
  for [flutter form builder](https://pub.dev/packages/flutter_form_builder)
version: 0.1.0
homepage: https://github.com/yfakariya/form_companion_presenter
repository: https://github.com/yfakariya/form_companion_presenter

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.5.0
  flutter:
    sdk: flutter
  flutter_form_builder : ^7.0.0
  form_companion_presenter: ^0.1.0
  meta: ^1.3.0

dev_dependencies:
  analyzer: ^3.0.0
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  form_field_builder_emitter:
    path: ../../tool/form_field_builder_emitter
  grinder: ^0.9.0
  path: ^1.8.0

dependency_overrides: {form_companion_presenter: {path: ../../packages/form_companion_presenter}}
