name: form_builder_companion_presenter
description: >
  Implements form_companion_presenter
  for Flutter FormBuilder (https://pub.dev/packages/flutter_form_builder)
version: 0.3.0
repository: https://github.com/yfakariya/form_companion_presenter

environment:
  sdk: ">=2.19.0 <3.0.0"
  # We use Form.maybeOf, which requries 3.7 and Form.of is changed with compatibility break.
  # So, we cannot support before 3.7.
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_form_builder : ^7.0.0
  form_companion_presenter: ^0.3.0
  meta: ^1.3.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
