name: ci

on:
  push:
    paths:
      - '**.dart'
      - 'pubspec.*'
      - 'analysis_options.yaml'
      - '.github/workflows/*.yml'
      - '.github/actions/**/*.yml'
  pull_request:
    paths:
      - '**.dart'
      - 'pubspec.*'
      - 'analysis_options.yaml'
      - '.github/workflows/*.yml'
      - '.github/actions/**/*.yml'

jobs:
  build-latest:
    runs-on: ubuntu-latest

    timeout-minutes: 15

    steps:
      # actions/checkout@v3.3.0
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
      - uses: ./.github/actions/build-and-test

  # Enables when newer stable version is released -- test each versions.
  # build-3_7:
  #   runs-on: ubuntu-latest

  #   timeout-minutes: 15

  #   steps:
  #     # actions/checkout@v3.3.0
  #     - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
  #     - uses: ./.github/workflows/actions/build-and-test
  #       with:
  #         flutter-version: '3.7'
