name: ci

on:
  push:
    paths:
      - '**.dart'
      - 'pubspec.*'
      - 'analysis_options.yaml'
      - '.github/workflows/ci.yaml'
  pull_request:
    paths:
      - '**.dart'
      - 'pubspec.*'
      - 'analysis_options.yaml'
      - '.github/workflows/ci.yaml'

jobs:
  build-latest:
    runs-on: ubuntu-latest

    timeout-minutes: 15

    steps:
      - uses: ./.github/workflows/actions/build-and-test

  # Enables when newer stable version is released -- test each versions.
  # build-3_7:
  #   runs-on: ubuntu-latest

  #   timeout-minutes: 15

  #   steps:
  #     - uses: ./.github/workflows/actions/build-and-test
  #       with:
  #         flutter-version: '3.7'