name: ci

on:
  push:
    branches:
      - master
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  schedule:
    # everyday at 09:00 (UTC) 
    - cron: "0 9 * * *"

jobs:
  build-latest:
    runs-on: ubuntu-latest

    timeout-minutes: 30

    steps:
      # actions/checkout@v3.3.0
      - uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f
      - uses: ./.github/actions/build-and-test

  # Enables when newer stable version is released -- test each versions.
  # build-3_7:
  #   runs-on: ubuntu-latest

  #   timeout-minutes: 15

  #   steps:
  #     # actions/checkout@v3.3.0
  #     - uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f
  #     - uses: ./.github/workflows/actions/build-and-test
  #       with:
  #         flutter-version: '3.7'
